title: Adedeji Oyefeso # your name (or website title) here
logo: "/images/Nice Picture of Me.PNG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Welcome to my website! My name is Adedeji, and I can describe myself as a dilligent college student who codes, invests in the stock market and loves to learn. 
  <br><br>
  Above all I strive to improve where I am lacking and make new friends. It is very important to know that you are never alone and will always need someone else to help you our with your journey. 
  <br><br>
  <a href="https://www.linkedin.com/in/adedeji-oyefeso-78a5451b1/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-N5T95CHCYQ # your Google Analytics tracking ID here
